@extends('master')
@section('title', 'Posts')
@section('content')
    <article>
        <h1><a href="/posts/my-first-post">My First Post</a></h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus dolor corporis debitis harum! Vero, officia velit obcaecati laboriosam quisquam delectus voluptatum saepe perferendis sit voluptates at, pariatur recusandae, vel excepturi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ratione consequuntur repellendus, maiores sapiente voluptatem quae molestias esse, nisi perferendis debitis. Officiis a, ut reiciendis quod sapiente temporibus eaque provident. At molestias facere itaque dolorum provident, magnam laborum sapiente quasi dolor doloremque molestiae iure, aspernatur libero atque quidem? Aspernatur velit autem architecto officia veritatis quas perspiciatis quam, molestiae voluptates corrupti doloremque fugit expedita incidunt hic accusamus atque? Vitae doloribus velit, nobis consequuntur unde commodi rerum omnis modi nostrum sit facilis non consequatur eaque at maxime consectetur maiores labore dolorum eos facere soluta quam dignissimos veniam voluptatibus! Unde similique, laudantium officiis culpa corporis iste, accusamus sunt vel quos dolores quisquam quas quae placeat vitae distinctio! Voluptatibus pariatur fuga omnis necessitatibus quaerat ducimus reiciendis unde distinctio exercitationem? Molestiae ea totam quas necessitatibus! Quia, cum commodi. Dolorem accusamus officiis quod dolore repellendus est obcaecati nostrum placeat mollitia. Labore laborum culpa provident nostrum alias, pariatur ad repudiandae recusandae qui. Facilis, quasi, aliquam id neque error doloribus impedit facere repellat vero ad obcaecati et voluptatibus eos saepe sit incidunt aut. Dicta consequuntur illum iusto? Velit repellendus cum ullam vitae itaque doloremque neque excepturi obcaecati, nisi, numquam aut enim atque quo reiciendis ut repellat! Fugit, officiis!</p>
    </article>

    <article>
        <h1><a href="/posts/my-second-post">My Second Post</a></h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus dolor corporis debitis harum! Vero, officia velit obcaecati laboriosam quisquam delectus voluptatum saepe perferendis sit voluptates at, pariatur recusandae, vel excepturi. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus odio autem saepe eius porro est illum itaque quam, necessitatibus error aliquid minus. Optio ut ad, vero pariatur quam, odio soluta molestiae amet velit minus itaque. Incidunt distinctio dolorum unde iusto, animi consequatur illo perspiciatis beatae aperiam labore, ducimus expedita ipsa odit corrupti excepturi officiis blanditiis. Repellat sunt earum expedita tempora quos dicta nulla nemo laboriosam enim iste excepturi, quod atque commodi ab odit aliquid consectetur rem provident eveniet dolore. Nesciunt vitae ex quisquam, cupiditate maxime hic impedit harum magni commodi, consequuntur possimus veritatis, tempore corrupti molestias blanditiis quia. Tempore rerum beatae, voluptate velit eos, ratione eum sunt quam nulla quae explicabo! Unde quas illum temporibus aspernatur, itaque cumque ex, provident vitae accusamus quod incidunt animi. Beatae fugit fuga pariatur cupiditate velit necessitatibus eum sint error, amet, similique asperiores alias repellat excepturi doloremque cum maiores. Architecto ex eaque vel accusantium mollitia voluptatum, esse, nam repellendus facere sapiente dicta illo deleniti enim eius et sed voluptate eum, non natus velit aperiam quasi minima. Molestias repellendus eius autem repellat accusantium ut voluptates vel reiciendis obcaecati natus aliquid at in facilis, quidem velit amet? Sunt adipisci debitis quia illum vitae omnis libero esse neque.</p>
    </article>


    <article>
        <h1><a href="/posts/my-third-post">My Third Post</a></h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus dolor corporis debitis harum! Vero, officia velit obcaecati laboriosam quisquam delectus voluptatum saepe perferendis sit voluptates at, pariatur recusandae, vel excepturi. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet quam cum ad porro qui, asperiores tempore delectus iure tempora consequuntur illum dignissimos reprehenderit laboriosam maiores, pariatur quas error iste in perspiciatis officia! Facilis fuga neque eveniet fugiat reiciendis. Optio exercitationem est dignissimos quisquam qui saepe ut? Dignissimos ipsum, delectus quam aliquam ipsa ducimus facilis in asperiores porro quis eos voluptates rerum maxime quisquam nemo reiciendis eligendi quibusdam ratione repudiandae consectetur maiores saepe vitae! Eligendi labore at corrupti aperiam expedita! Distinctio asperiores, dolorum sit iure nesciunt laboriosam iste odit eaque eius beatae magni, vero blanditiis odio suscipit laudantium esse maxime ipsum consequatur sed facere. Fugit atque tempora cumque. Perspiciatis, dolorem est impedit quis nesciunt earum deleniti, amet hic repellendus fugiat quaerat quidem tenetur delectus sunt, dignissimos explicabo aperiam facilis distinctio consectetur? Asperiores temporibus dolor dignissimos! Nesciunt, eos, ducimus ipsam optio hic velit sapiente harum illum adipisci obcaecati vel, ad voluptas blanditiis similique! Magni ea, nostrum, adipisci eligendi veniam consequatur optio odit, dignissimos natus reprehenderit ducimus numquam corporis minus veritatis. Suscipit odit voluptatum labore! Alias dicta voluptas mollitia natus eius cupiditate explicabo! Perferendis architecto sapiente minus nobis tempore dicta. Maxime libero ab voluptate minima corrupti, qui consequatur neque tempore cumque aperiam blanditiis?</p>
    </article>
@endsection